### PR TITLE
Added omittable steps

### PR DESCRIPTION
**Pull request by ercsctt**
Issue reference: #43 

Please let me know if there's anything I can change here, I've tried to implement this in the most elegant way without having to modify a bunch of logic. I needed this for a personal project, and it works fine as is (afaik), but if there's a better way of doing this without rewriting the entire wizard logic let me know 😂

### CODE REVIEW

**Comment by ksassnowski** [comment]
I took a quick glance at the changes and I think I agree with the overall design. I think `availableSteps` needs to be cached somehow, so we aren't looping over the steps over and over again. Especially since the `omit` method of a step can contain arbitrary code (like a network call). I also think that we should pass the current request to the `availableSteps` method.

I'll have a closer look at this in the next few days

**Comment by ksassnowski** [comment]
I meant caching for the current request. For instance, both the `summary` and `nextStep` methods currently call `availableSteps`. Since the response renderers will likely want to call the `summary` method, we'd essentially be doing double the work for no reason.

I think `availableSteps` should be lazily calculated and return the cached value if it has already been computed before. Might have to think about invalidating the cache, i.e. force a recompute, after the wizard's data has changed.

**Comment by Wulfheart** [comment]
This feature would be really nice indeed.

**Comment by ksassnowski** [comment]
I’ll look at this once I’m back from vacation

**Comment by ksassnowski** [comment]
I've made couple of small changes to the PR. Most notably, I implemented the memoization of the available steps myself as I would rather not pull in a whole other dependency just for that. I also added a few extra tests to for the wizard and wizard repository.

Other than that, looks good to me. Thanks for the contribution!

**Pull request merged**
