### PR TITLE
Support Laravel 9 too

### PR DESCRIPTION
**Pull request by ziming**

### CODE REVIEW

**Comment by ziming** [comment]
hello! anything else I could do to get this merged faster? :)

**Comment by marcreichel** [comment]
Sadly, Arcanist was the only package which blocked me from updating to Laravel 9, so I will use my fork with the adjusted `composer.json` instead now.

It's sad to see @ksassnowski seems to not care about this package anymore.

**Comment by ksassnowski** [comment]
Thanks @ziming ! Sorry for the delay.

@marcreichel save the guilt trip bullshit, please. This ain't my job and real life happens sometimes.

**Comment by marcreichel** [comment]
@ksassnowski Wasn't meant offending. Sorry if you thought it was. ❤️

**Pull request merged**
