### PR TITLE
Support Laravel 10

### PR DESCRIPTION
**Pull request by ziming**
Laravel 10 coming on Feb 7

### CODE REVIEW

**Comment by ksassnowski** [comment]
Thanks! Looks like the actions are failing, though. Can you have a look at that?

**Comment by ziming** [comment]
laravel 10 & testbench 8 r not officially tagged as new release yet could be why.

also this package has a composer.lock file that may affect the end results.

**Comment by ziming** [comment]
@ksassnowski 

**1.  run-phpstan / PHPStan (pull_request)**

> The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update --lock`.
Script composer normalize handling the post-install-cmd event returned with error code 1

Can I try delete the composer.lock file to see if it resolve this?

**2. run-tests / P8.0 - L10.* - prefer-lowest - ubuntu-latest (pull_request)**

> Run composer require "laravel/framework:10.*" "orchestra/testbench:" "nunomaduro/larastan:" --no-interaction --no-update
Error: Option orchestra/testbench is missing a version constraint, use e.g. orchestra/testbench:^1.0

I think it is because testbench ^8.0 is not tagged or released yet. Shall we wait until after laravel 10 is officially out then re run the actions for this PR?

3. run-tests / P8.2 - L10.* - prefer-lowest - ubuntu-latest (pull_request) 

Same as 2.

**Comment by ksassnowski** [comment]
I fixed the pipeline and pushed the commits. Thanks for the contribution!

**Pull request merged**
